# 初めての自作プラグイン #
[[plugins]]
repo = 'Daiki48/hello-daiki'
on_cmd = 'DenopsDaiki'

# fzf
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = 'nvim-web-devicons'
on_event = 'BufEnter'
hook_source = '''lua require('telescope.telescope')'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
on_source = 'telescope.nvim'

# markdown preview
[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'VonHeikemen/searchbox.nvim'
on_source = 'nui.nvim'
hook_add = '''
nnoremap / <cmd>SearchBoxIncSearch<CR>
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''lua require('treesitter.treesitter')'''

[[plugins]]
repo = 'yioneko/nvim-yati'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_source = 'nvim-treesitter'

# brackets
[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = ['InsertEnter']
hook_post_source = '''lua require('treesitter.autopairs')'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'vue', 'html', 'jsx', 'tsx', 'css', 'scss', 'json', 'markdown']
hook_add = '''
source ~/.config/nvim/plugins/vim-prettier.rc.vim
'''

[[plugins]]
repo = 'skanehira/jumpcursor.vim'
hook_add = '''
map ;j <Plug>(jumpcursor-jump)
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_event = 'FileType'
hook_source = '''lua require 'colorizer'.setup()'''

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'
on_cmd = 'VimHelpGenerator'
hook_add = '''
let g:vimhelpgenerator_defaultlanguage = "en"
let g:vimhelpgenerator_content = {
	\ 'contents': 1, 'introduction': 1, 'usage': 1, 'interface': 1,
	\ 'variables': 1, 'commands': 1, 'key-mappings': 1, 'functions': 1,
	\ 'setting': 1, 'todo': 0, 'changelog': 1,}
let g:vimhelpgenerator_author = 'Author  : Daiki Nakashima <daiki48.engineer at gmail.com>'
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'InsertEnter'
hook_post_source = '''lua require('lsp.lspconfig')'''

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'


