# filer #
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#default_hidden=1
nnoremap <silent><C-n> :Fern .<CR>
nmap <silent> b <BS><CR>

function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_settings()
augroup END
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = 'fern.vim'
hook_source = '''
let g:fern#renderer='nerdfont'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_source = 'fern.vim'
hook_source = '''
set encoding=utf8
set guifont=Hack_Nerd_Font:h15
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_source = '''
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
'''

# 初めての自作プラグイン #
[[plugins]]
repo = 'Daiki48/hello-daiki'

# HTML closetag #
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
source ~/.config/nvim/plugins/closetag.rc.vim
'''

# fzf
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_source = 'telescope.nvim'

# comp
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
call ddc#custom#patch_global('sources', ['nvim-lsp', 'around'])
call ddc#custom#patch_global('completionMenu', 'pum.vim')
call ddc#custom#patch_global('sourceOptions', {
\ '_': {
\   'matchers': ['matcher_head'],
\   'sorters': ['sorter_rank']},
\ 'around': {
\   'mark': 'around' },
\ 'nvim-lsp': {
\   'mark': 'lsp',
\   'forceCompletionPattern': '\.\w*|:\w*|->\w*' },
\ })
call ddc#enable()
inoremap <Tab> <Cmd>call pum#map#select_relative(+1)<CR>
inoremap <S-Tab> <Cmd>call pum#map#select_relative(-1)<CR>
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc.vim'

# markdown preview
[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = ['markdown']

