# filer #
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#default_hidden=1
nnoremap <silent><C-n> :Fern .<CR>
nmap <silent> b <BS><CR>

function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_settings()
augroup END
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

# 初めての自作プラグイン #
[[plugins]]
repo = 'Daiki48/hello-daiki'

# 補完関係 #
# [[plugins]]
# repo = 'Shougo/ddc.vim'
# on_event = 'InsertEnter'
# depends = ['denops.vim']
# hook_source = '''
# call ddc#custom#patch_global('sources', ['nvim-lsp', 'around'])
# call ddc#custom#patch_global('sourceOptions', {
#   \ '_': {
#     \ 'matchers': ['matcher_head'],
#     \ 'sorters': ['sorter_rank']
#   \ },
#   \ 'around': {
#     \ 'mark': 'A'
#   \ }, 
#   \ 'nvim-lsp': {
#     \ 'mark': 'L',
#     \ 'forceCompletionPattern': '\.\w*|:\w*|->\w*'
#   \ },
# \ })
# call ddc#enable()
# '''

# # 現在の行の周辺の単語を候補として抽出してくれる #
# [[plugins]]
# repo = 'Shougo/ddc-around'
# on_source = 'ddc.vim'

# # 入力中の文字列に基づいて候補から絞り込みを行う #
# [[plugins]]
# repo = 'Shougo/ddc-matcher_head'
# on_source = 'ddc.vim'

# # 候補の一覧をマッチした順・すでに入力されている順でソートする #
# [[plugins]]
# repo = 'Shougo/ddc-sorter_rank'
# on_source = 'ddc.vim'

# # language server #
# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp'
# on_source = 'ddc.vim'

# lsp
# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# on_event = 'BufEnter'
# hook_source = '''
# lua << EOF
# local lsp_installer = require("nvim-lsp-installer")
# lsp_installer.on_server_ready(function(server)
#   local opts = {}
#   server:setup(opts)
#   vim.cmd [[ do User LspAttachBuffers ]]
# end)
# EOF
# '''

# [[plugins]]
# repo = 'williamboman/nvim-lsp-installer'
# on_source = 'nvim-lspconfig'

# HTML closetag #
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
source ~/.config/nvim/plugins/closetag.rc.vim
'''

# fzf
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'

