[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><C-n> :NERDTree<CR>
'''

# 初めての自作プラグイン #
[[plugins]]
repo = 'Daiki48/hello-daiki'

# 補完関係 #
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
call ddc#custom#patch_global('sources', ['nvim-lsp', 'around', 'nextword'])
call ddc#custom#patch_global('sourceOptions', {
  \ '_': {
    \ 'matchers': ['matcher_head'],
    \ 'sorters': ['sorter_rank']
  \ },
  \ 'around': {
    \ 'mark': 'A'
  \ }, 
  \ 'nvim-lsp': {
    \ 'mark': 'L',
    \ 'forceCompletionPattern': '\.\w*|:\w*|->\w*'
  \ },
  \ 'nextword': {
    \ 'mark': 'NW',
  \ },
\ })
call ddc#custom#patch_global('sourceParams', {
	\	'nvim-lsp': { 'kindLabels': { 'Class': 'c' } },
	\	})
call ddc#enable()
'''

# 現在の行の周辺の単語を候補として抽出してくれる #
[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nextword'
on_source = 'ddc.vim'

# 入力中の文字列に基づいて候補から絞り込みを行う #
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

# 候補の一覧をマッチした順・すでに入力されている順でソートする #
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

# HTMLの閉じタグを生成する #
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
" filenames like *.xml, *.html, *.xhtml, ...
" These are the file extensions where this plugin is enabled.
"
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.tsx,*.jsx,*.ts,*.js'

" filenames like *.xml, *.xhtml, ...
" This will make the list of non-closing tags self-closing in the specified files.
"
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.tsx,*.js,*.ts'

" filetypes like xml, html, xhtml, ...
" These are the file types where this plugin is enabled.
"
let g:closetag_filetypes = 'html,xhtml,phtml,jsx,tsx,js,ts'

" filetypes like xml, xhtml, ...
" This will make the list of non-closing tags self-closing in the specified files.
"
let g:closetag_xhtml_filetypes = 'xhtml,jsx,tsx,js,ts'

" integer value [0|1]
" This will make the list of non-closing tags case-sensitive (e.g. `<Link>` will be closed while `<link>` won't.)
"
let g:closetag_emptyTags_caseSensitive = 1

" dict
" Disables auto-close if not in a "valid" region (based on filetype)
"
let g:closetag_regions = {
    \ 'typescript.tsx': 'jsxRegion,tsxRegion',
    \ 'javascript.jsx': 'jsxRegion',
    \ 'typescriptreact': 'jsxRegion,tsxRegion',
    \ 'javascriptreact': 'jsxRegion',
    \ }

" Shortcut for closing tags, default is '>'
"
let g:closetag_shortcut = '>'

" Add > at current position without closing the current tag, default is ''
"
let g:closetag_close_shortcut = '<leader>>'
'''


# filer #
[[plugins]]
repo = 'Shougo/ddu.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
source ~/.config/nvim/plugins/ddu.rc.vim
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

