# 初めての自作プラグイン #
[[plugins]]
repo = 'Daiki48/hello-daiki'

# HTML closetag #
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
source ~/.config/nvim/plugins/closetag.rc.vim
'''

# fzf
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_source = 'telescope.nvim'

# markdown preview
[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'VonHeikemen/searchbox.nvim'
on_source = 'nui.nvim'
hook_add = '''
nnoremap / <cmd>SearchBoxIncSearch<CR>
'''

