[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
colorscheme iceberg
'''

# statusline & tabline #
[[plugins]]
repo = 'hoob3rt/lualine.nvim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'vue', 'html', 'tsx', 'css', 'scss', 'json', 'markdown']
hook_add = '''
source ~/.config/nvim/plugins/vim-prettier.rc.vim
'''

# 縦移動 #
[[plugins]]
repo = 'skanehira/jumpcursor.vim'
hook_add = '''
map ;j <Plug>(jumpcursor-jump)
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'neovim/nvim-lsp'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

# [[plugins]]
# repo = 'williamboman/nvim-lsp-installer'
# on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

[[plugins]]
repo = 'yioneko/nvim-yati'
on_source = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'

[[plugins]]
repo = 'dense-analysis/ale'
# hook_add = '''
# source ~/.config/nvim/plugins/ale.rc.vim
# '''

