[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Daiki48/coolnessFlair.vim'
hook_add = '''
colorscheme coolnessFlair
'''

# statusline & tabline #
[[plugins]]
repo = 'hoob3rt/lualine.nvim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'neovim/nvim-lsp'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'rcarriga/nvim-notify'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'


